--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.127.0
-- Product Home Page: http://www.devart.com/dbforge/sql/studio
-- Script date 12/23/2021 9:44:24 PM
-- Target server version: 15.00.2080
-- Target connection string: Data Source=TRHUTRONG;Encrypt=False;Initial Catalog=QLHD;Integrated Security=True;User ID=TRHUTRONG\ADMIN
--



SET LANGUAGE 'English'
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

--
-- Backing up database Nhom18_DoAnThucHanh_19HTT2_1
--
--
-- Create backup folder
--
IF OBJECT_ID('xp_create_subdir') IS NOT NULL
  EXEC xp_create_subdir N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup'
--
-- Backup database to the file with the name: <database_name>_<yyyy>_<mm>_<dd>_<hh>_<mi>.bak
--
DECLARE @db_name SYSNAME
SET @db_name = N'Nhom18_DoAnThucHanh_19HTT2_1'

DECLARE @filepath NVARCHAR(4000)
SET @filepath =
/*define base part*/ N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\' + @db_name + '_' +
/*append date*/ REPLACE(CONVERT(NVARCHAR(10), GETDATE(), 102), '.', '_') + '_' +
/*append time*/ REPLACE(CONVERT(NVARCHAR(5), GETDATE(), 108), ':', '_') + '.bak'

DECLARE @SQL NVARCHAR(MAX)
SET @SQL = 
    N'BACKUP DATABASE ' + QUOTENAME(@db_name) + ' TO DISK = @filepath WITH INIT' + 
      CASE WHEN EXISTS(
                SELECT value
                FROM sys.configurations
                WHERE name = 'backup compression default'
          )
        THEN ', COMPRESSION'
        ELSE ''
      END

EXEC sys.sp_executesql @SQL, N'@filepath NVARCHAR(4000)', @filepath = @filepath
GO

USE Nhom18_DoAnThucHanh_19HTT2_1
GO

IF DB_NAME() <> N'Nhom18_DoAnThucHanh_19HTT2_1' SET NOEXEC ON
GO
--
-- Delete data from the table 'dbo.TX_DH'
--
TRUNCATE TABLE dbo.TX_DH
GO
--
-- Delete data from the table 'dbo.TKTAIXE'
--
TRUNCATE TABLE dbo.TKTAIXE
GO
--
-- Delete data from the table 'dbo.TKNHANVIEN'
--
TRUNCATE TABLE dbo.TKNHANVIEN
GO
--
-- Delete data from the table 'dbo.TKKhachHang'
--
TRUNCATE TABLE dbo.TKKhachHang
GO
--
-- Delete data from the table 'dbo.TKDoanhNghiep'
--
TRUNCATE TABLE dbo.TKDoanhNghiep
GO
--
-- Delete data from the table 'dbo.DONHANG_SP'
--
TRUNCATE TABLE dbo.DONHANG_SP
GO
--
-- Delete data from the table 'dbo.DH_KH'
--
TRUNCATE TABLE dbo.DH_KH
GO
--
-- Delete data from the table 'dbo.CHINHANH_SP'
--
TRUNCATE TABLE dbo.CHINHANH_SP
GO
--
-- Delete data from the table 'dbo.DonHang'
--
DELETE dbo.DonHang
GO
--
-- Delete data from the table 'dbo.ChiNhanh'
--
DELETE dbo.ChiNhanh
GO
--
-- Delete data from the table 'dbo.HopDong'
--
DELETE dbo.HopDong
GO
--
-- Delete data from the table 'dbo.DoanhNghiep'
--
DELETE dbo.DoanhNghiep
GO
--
-- Delete data from the table 'dbo.TAIXE'
--
DELETE dbo.TAIXE
GO
--
-- Delete data from the table 'dbo.SANPHAM'
--
DELETE dbo.SANPHAM
GO
--
-- Delete data from the table 'dbo.NHANVIEN'
--
DELETE dbo.NHANVIEN
GO
--
-- Delete data from the table 'dbo.LOAIHANG'
--
DELETE dbo.LOAIHANG
GO
--
-- Delete data from the table 'dbo.KhuVucHoatDong'
--
TRUNCATE TABLE dbo.KhuVucHoatDong
GO
--
-- Delete data from the table 'dbo.KhachHang'
--
DELETE dbo.KhachHang
GO

--
-- Inserting data into table dbo.KhachHang
--
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0000', N'Bằng Sơn', '033-2693', 'Cách Mạng Tháng 8', 'nubfsafr1@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0001', N'Gia Ðức', '134-4990', 'Nguyễn Trãi', 'Pollard@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0002', N'Bảo An', '582-1898', 'Nguyễn Văn Cừ', 'Myrtle_Bisson@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0003', N'Gia Hiệp', '456-3913', 'Lê Lai', 'Pendergrass@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0004', N'Trà My', '436-5187', 'Cộng Hòa', 'eewhz4722@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0005', N'Yên Sơn', '059-8668', 'An Dương Vương', 'Carrol_Abbott@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0006', N'Thất Dũng', '858-1826', 'Trường Chinh', 'ArmandaAntoine@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0007', N'Quỳnh Trang', '927-6368', 'Âu Cơ', 'Beard1@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0008', N'Hà Mi', '485-8556', 'Hùng Vương', 'ezhb04@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0009', N'Bảo Bảo', '164-0359', 'Lê Lợi', 'qsquhppx4@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0010', N'Trâm Anh', '735-4252', 'Lý Chính Thắng', 'Gist33@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0011', N'Quỳnh Trâm', '236-3127', 'Nguyễn Thị Minh Khai', 'RolandoSepulveda87@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0012', N'Gia Hòa', '944-6324', 'Trần Hưng Đạo', 'Harrell@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0013', N'Mỹ Vân', '070-3554', 'Nguyễn Trãi', 'Herrmann@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0014', N'Trâm Oanh', '169-9500', 'Cộng Hòa', 'Costa@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0015', N'Quỳnh Vân', '957-8209', 'Cách Mạng Tháng 8', 'Adolfo.Burchfield@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0016', N'Bảo Chấn', '666-4334', 'Lê Lai', 'RefugioP.Daigle658@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0017', N'Gia Hoàng', '852-9984', 'An Dương Vương', 'uqvvha5071@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0018', N'Bảo Ðịnh', '850-3965', 'Âu Cơ', 'ErwinWetzel779@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0019', N'Nhật Hùng', '226-6746', 'Nguyễn Văn Cừ', 'Guidry@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0020', N'Phương Chi', '603-7497', 'Lê Lợi', 'MaryannaBynum@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0021', N'hánh Giao', '882-3699', 'Lý Chính Thắng', 'Oliver37@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0022', N'Thất Thọ', '756-1265', 'Trường Chinh', 'Tate738@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0023', N'Mỹ Xuân', '706-5283', 'Trần Hưng Đạo', 'TawnaBanuelos@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0024', N'Hà My', '932-9916', 'Hùng Vương', 'WinstonBurgess@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0025', N'Nhật Huy', '156-3135', 'Nguyễn Thị Minh Khai', 'Nicholas_Latham@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0026', N'Trân Châu', '987-7426', 'Cách Mạng Tháng 8', 'AbelGreenberg34@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0027', N'Sao Băng', '264-7463', 'Nguyễn Văn Cừ', 'AdelaM_Bayne@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0028', N'hánh Huyền', '114-1967', 'Nguyễn Trãi', 'mkvf03@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0029', N'Gia Huấn', '035-4453', 'Lê Lợi', 'LucioIAndres@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0030', N'Thế An', '853-2657', 'Lê Lai', 'AugustinaFerrer746@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0031', N'An Bình', '617-1311', 'Trần Hưng Đạo', 'Abbie_Pickett975@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0032', N'Trúc Chi', '448-9195', 'Trường Chinh', 'HoustonChristy@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0033', N'Hà Nhi', '306-1438', 'An Dương Vương', 'SueannTibbetts963@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0034', N'Bảo Duy', '894-1323', 'Hùng Vương', 'TomasAbraham373@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0035', N'Sao Mai', '391-8579', 'Cộng Hòa', 'Cousins11@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0036', N'An Di', '388-9238', 'Âu Cơ', 'LatriciaGilbert@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0037', N'Nhật Khương', '109-0825', 'Lý Chính Thắng', 'Wenona_Fairbanks@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0038', N'Mỹ Yến', '004-6712', 'Nguyễn Thị Minh Khai', 'Lawless@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0039', N'Trúc Lam', '699-1597', 'Nguyễn Văn Cừ', 'LucienAlexander@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0040', N'Gia Hùng', '959-8735', 'Cách Mạng Tháng 8', 'FloyLira@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0041', N'Bảo Giang', '051-3675', 'Nguyễn Trãi', 'nmefrz9672@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0042', N'Hà Phương', '110-7224', 'Cộng Hòa', 'Aguilar987@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0043', N'An Hạ', '675-2579', 'Lê Lai', 'SpencerS6@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0044', N'Song Kê', '402-7217', 'Âu Cơ', 'WendieAleman838@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0045', N'Thế Anh', '261-4873', 'An Dương Vương', 'Mead@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0046', N'Trúc Lan', '131-0435', 'Trường Chinh', 'iigoumm57@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0047', N'Hà Thanh', '629-1253', 'Lý Chính Thắng', 'AllredS@customer.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0048', N'Nhật Minh', '987-4982', 'Hùng Vương', 'ShondraStpierre619@client.hcmus')
INSERT dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0049', N'Gia Hưng', '242-4845', 'Lê Lợi', 'Allison@client.hcmus')
GO

--
-- Inserting data into table dbo.KhuVucHoatDong
--
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV000', N'Phú Tài')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV001', N'Thủ Đức')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV002', N'Bến Lức')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV003', N'4')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV004', N'Tân Bình')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV005', N'3')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV006', N'1')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV007', N'Tân Phú')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV008', N'2')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV009', N'Phú Hải')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV010', N'8')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV011', N'Bình Tân')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV012', N'7')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV013', N'12')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV014', N'Tam Hiệp')
INSERT dbo.KhuVucHoatDong(MAKHUVUC, TENKHUVUC) VALUES (N'KV015', N'Đống Đa')
GO

--
-- Inserting data into table dbo.LOAIHANG
--
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH000', N'Accessories')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH001', N'Electronics')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH002', N'Beauty')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH003', N'Automotive')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH004', N'Automotive')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH005', N'Clothing')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH006', N'Health')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH007', N'Tools')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH008', N'Food')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH009', N'Audible')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH010', N'Gifts')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH011', N'Computers')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH012', N'Computers')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH013', N'Pets')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH014', N'Beauty')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH015', N'Shoes')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH016', N'Clothing')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH017', N'Gifts')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH018', N'Automotive')
INSERT dbo.LOAIHANG(MALOAIHANG, TENLOAIHANG) VALUES (N'LH019', N'Games')
GO

--
-- Inserting data into table dbo.NHANVIEN
--
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV000', N'Giao Linh', 'Lý Chính Thắng', 'Reinaldo_Goforth@nmcnpm.hcmus', '(173) 913-3413')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV001', N'inh Vy', 'Trường Chinh', 'DaniloBello@nhom18.hcmus', '(246) 801-3259')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV002', N'Hải Yến', 'An Dương Vương', 'MyriamMoen2@nhom18.hcmus', '(932) 898-4866')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV003', N'Việt Khoa', 'Hùng Vương', 'Cuevas77@nhom18.hcmus', '(432) 029-0917')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV004', N'Công Thành', 'Cách Mạng Tháng 8', 'Akin28@nhom18.hcmus', '(774) 701-4681')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV005', N'Hoàng Việt', 'Nguyễn Trãi', 'SuzanFox341@nhom18.hcmus', '(333) 883-8602')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV006', N'Nguyên Bảo', 'Nguyễn Văn Cừ', 'NelleConroy@nhom18.hcmus', '(926) 566-1841')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV007', N'Thy Vân', 'Cộng Hòa', 'WarnerVelasco99@nmcnpm.hcmus', '(370) 344-0452')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV008', N'Giáng Ngọc', 'Âu Cơ', 'Zeigler251@nhom18.hcmus', '(722) 646-3689')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV009', N'Thành Phương', 'Lê Lợi', 'Willoughby@nhom18.hcmus', '(102) 037-4035')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV010', N'inh Xuân', 'Trần Hưng Đạo', 'MicahDecker413@nmcnpm.hcmus', '(856) 058-0791')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV011', N'Nguyên Bổng', 'Lê Lai', 'Hinton@nmcnpm.hcmus', '(509) 470-4250')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV012', N'Việt Khôi', 'Nguyễn Thị Minh Khai', 'ThomsonZ@nhom18.hcmus', '(877) 263-6256')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV013', N'Giáng Tiên', 'Lý Chính Thắng', 'pwfv2198@nmcnpm.hcmus', '(254) 060-0952')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV014', N'Hải Ân', 'An Dương Vương', 'Genesis.Hollingsworth5@nhom18.hcmus', '(288) 754-6475')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV015', N'inh Yến', 'Nguyễn Trãi', 'ArchieOneill@nmcnpm.hcmus', '(931) 389-6203')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV016', N'Công Tráng', 'Trường Chinh', 'mkwr2678@nhom18.hcmus', '(617) 769-0203')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV017', N'Thanh Quang', 'Hùng Vương', 'CesarV.Madison@nhom18.hcmus', '(271) 270-0532')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV018', N'Hải Ðường', 'Nguyễn Thị Minh Khai', 'ChaseFierro455@nhom18.hcmus', '(672) 875-2517')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV019', N'Hoàng Xuân', 'Lê Lai', 'Cross@nhom18.hcmus', '(583) 772-4246')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV020', N'inh Đan', 'Nguyễn Văn Cừ', 'Ackerman832@nhom18.hcmus', '(107) 732-9842')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV021', N'Hảo Nhi', 'Lê Lợi', 'ChloeAcker@nhom18.hcmus', '(194) 459-0650')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV022', N'ậu Xuân', 'Cộng Hòa', 'Bebe_Stjohn@nhom18.hcmus', '(761) 059-8365')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV023', N'Công Tuấn', 'Cách Mạng Tháng 8', 'Estell.Anthony@nhom18.hcmus', '(126) 738-2399')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV024', N'Hằng Anh', 'Âu Cơ', 'JacintoRagland@nmcnpm.hcmus', '(589) 676-9063')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV025', N'Việt Long', 'Trần Hưng Đạo', 'Badger@nhom18.hcmus', '(467) 315-2656')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV026', N'Hồng Ðăng', 'An Dương Vương', 'BrandonToledo@nhom18.hcmus', '(554) 139-6837')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV027', N'ộc Miên', 'Lý Chính Thắng', 'RolandArrington1@nhom18.hcmus', '(559) 175-5936')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV028', N'Nguyên Ðan', 'Nguyễn Văn Cừ', 'Talley29@nhom18.hcmus', '(772) 424-9243')
INSERT dbo.NHANVIEN(MANV, HOTEN, DIACHI, EMAIL, SDT) VALUES (N'NV029', N'Thành Sang', 'Trường Chinh', 'MatthewZBach64@nmcnpm.hcmus', '(324) 514-7560')
GO

--
-- Inserting data into table dbo.SANPHAM
--
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP73373', N'Bicordon', 900.6965)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP76401', N'Suplictedger', 621.638)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP95334', N'Stereotinator', 282.2985)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP89475', N'Tabtopaquator', 721.5381)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP71060', N'Conniedgphone', 800.7967)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP79902', N'Printculletor', 621.6381)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP51811', N'Translifiimentor', 721.5382)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP00526', N'Armtaicer', 382.1986)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP32085', N'Amplifiicator', 900.6966)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP02703', N'Micleanentor', 282.2986)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP24345', N'Reculra', 621.6382)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP02876', N'Transtoperry', 405.4379)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP25169', N'Monnira', 382.1987)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP61357', N'Monobandpler', 282.2987)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP71979', N'Prolifientor', 180.6955)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP64934', N'Playtinoner', 382.1988)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP33597', N'Armcyclar', 282.2988)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP28474', N'Comwoofer', 721.5383)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP84310', N'Printnifiscope', 80.7955)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP89139', N'Antopleton', 505.338)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP27463', N'Printcordry', 180.6956)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP87544', N'Cleantectinentor', 405.438)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP08107', N'Charplottra', 80.7956)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP04014', N'Tabpickphone', 180.6957)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP60103', N'Subholdplridge', 505.3381)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP63609', N'Subcordor', 382.1989)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP12676', N'Tabcordoner', 405.4381)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP28805', N'Tabwoofridge', 621.6383)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP15360', N'Supbandry', 800.7968)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP02926', N'Cartcyclon', 505.3382)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP01706', N'Stereoleor', 405.4382)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP95459', N'Recessator', 505.3383)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP86452', N'Cleanjectimer', 721.5384)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP78869', N'Armleer', 282.2989)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP88236', N'Readholdor', 621.6384)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP98017', N'Armnion', 382.199)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP02002', N'Compickewator', 721.5385)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP01820', N'Commutopra', 80.7957)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP39031', N'Monotaedger', 282.299)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP21544', N'Stereopickader', 900.6967)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP25694', N'Sublifiommscope', 800.7969)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP65571', N'Supbandor', 621.6385)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP52544', N'Comtinentor', 405.4383)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP24645', N'Comlifiadon', 900.6968)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP18429', N'Tabmutra', 505.3384)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP92943', N'Printputor', 405.4384)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP55253', N'Cleancorder', 505.3385)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP72190', N'Tweetmutry', 721.5386)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP30011', N'Telictor', 621.6386)
INSERT dbo.SANPHAM(MASP, TENSP, GIA) VALUES (N'SP99221', N'Comleepon', 405.4385)
GO

--
-- Inserting data into table dbo.TAIXE
--
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX000', N'Huyền Thư', N'Nguyễn Thị Minh Khai', 'Jose_Reddick@driver.nhom18.hcmus', 'B0075GQTH2', '5445619486823734', N'4', '03790369660')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX001', N'Lâm Uyên', N'Nguyễn Văn Cừ', 'HylandZ@driver.nmcnpm.hcmus', 'B00AEA6GU0', '6371987821172026', N'Bình Tân', '03069387330')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX002', N'Xuân Minh', N'Cách Mạng Tháng 8', 'Corley@driver.nhom18.hcmus', 'B0080KPW25', '4508582713365506', N'7', '03741395459')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX003', N'Quý Khánh', N'Âu Cơ', 'StantonMorrell@driver.nmcnpm.hcmus', 'B00L63717J', '6227784832157997', N'Thủ Đức', '03721335643')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX004', N'Huyền Trang', N'Trường Chinh', 'vblago6610@driver.nhom18.hcmus', 'B00OO8HIT2', '6224046936831858', N'Tân Bình', '03414594378')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX005', N'hi Phi', N'Hùng Vương', 'LudivinaOKlinger@driver.nmcnpm.hcmus', 'B0098371BD', '3537310482259578', N'11', '03461783784')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX006', N'Xuân Nam', N'Lê Lợi', 'BennyCarswell@driver.nhom18.hcmus', 'B00VNUR445', '5311009206676342', N'Tân Phú', '03494195541')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX007', N'Lê Quỳnh', N'Lý Chính Thắng', 'Burns26@driver.nmcnpm.hcmus', 'B00O0U823N', '3570138516333749', N'6', '03010466774')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX008', N'Tố Nga', N'Cộng Hòa', 'Needham@driver.nhom18.hcmus', 'B009FP26P2', '4508040734545572', N'8', '03409837300')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX009', N'Thiên Tuyền', N'Lê Lai', 'Nicolas.Pinkston659@driver.nhom18.hcmus', 'B004BPYDZ5', '6381429294064230', N'Tam Hiệp', '03061882882')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX010', N'Tố Nhi', N'An Dương Vương', 'AdolfoShearer@driver.nmcnpm.hcmus', 'B00GDQ1KTY', '3556548996163481', N'Đống Đa', '03430284971')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX011', N'hi Phượng', N'Nguyễn Trãi', 'BillyDollar364@driver.nmcnpm.hcmus', 'B002LH6V8I', '379357731140106', N'Phú Hải', '03078718793')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX012', N'Minh Hỷ', N'Trần Hưng Đạo', 'Bowser@driver.nhom18.hcmus', 'B00BT19KKR', '6377758468687137', N'3', '03449164393')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX013', N'Anh Việt', N'Lê Lai', 'Hornsby@driver.nhom18.hcmus', 'B00YXBG3W6', '5374966332278539', N'Bến Lức', '03413441494')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX014', N'Huyền Trâm', N'Cách Mạng Tháng 8', 'piqekrhg_wugxtgil@driver.nhom18.hcmus', 'B00NEKOHPX', '6225167724657575', N'2', '03338835523')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX015', N'Lưu Ly', N'Nguyễn Văn Cừ', 'Gardiner@driver.nhom18.hcmus', 'B006ZJWG77', '5375085981387696', N'1', '03006517136')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX016', N'Thiếu Mai', N'An Dương Vương', 'AdeleKozlowski5@driver.nhom18.hcmus', 'B00Q4975T7', '5306608225539451', N'9', '03437015908')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX017', N'Xuân Ninh', N'Nguyễn Trãi', 'jtgfnbwz6964@driver.nhom18.hcmus', 'B003401DZF', '5123206337921005', N'Phú Nhuận', '03773848055')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX018', N'Tố Quyên', N'Lê Lợi', 'TrotterZ@driver.nhom18.hcmus', 'B00AALEUG5', '6200436289606148', N'Cầu Giấy', '03710651610')
INSERT dbo.TAIXE(MATX, HOTEN, DIACHI, EMAIL, BIENSOXE, TKNH, KHUVUCHD, SDT) VALUES (N'TX019', N'Thiều Ly', N'Trần Hưng Đạo', 'Hector.Ackerman74@driver.nhom18.hcmus', 'B00NRNN3QO', '6226470297592297', N'5', '03375646374')
GO

--
-- Inserting data into table dbo.DoanhNghiep
--
INSERT dbo.DoanhNghiep(MaSoThue, LoaiHang, DiaChiKinhDoanh, QUAN, TenDoanhNghiep, NguoiDaiDien, ThanhPho, SoDT, Email, SLDonHang) VALUES (N'DN37', 'LH016', N'Nguyễn Trãi', N'2', N'USPS Priority Mail', N'Thương Huyền', N'Hà Nội', '+44 9241 09 191', 'rmfz953@example.com', 756)
INSERT dbo.DoanhNghiep(MaSoThue, LoaiHang, DiaChiKinhDoanh, QUAN, TenDoanhNghiep, NguoiDaiDien, ThanhPho, SoDT, Email, SLDonHang) VALUES (N'DN03', 'LH008', N'Nguyễn Văn Cừ', N'Cầu Giấy', N'Airmail Economy', N'Ái Thy', N'Hồ Chí Minh', '+971 8 434 8120', 'StuartZ.Kinder@nowhere.com', 154)
INSERT dbo.DoanhNghiep(MaSoThue, LoaiHang, DiaChiKinhDoanh, QUAN, TenDoanhNghiep, NguoiDaiDien, ThanhPho, SoDT, Email, SLDonHang) VALUES (N'DN71', 'LH011', N'Lê Lợi', N'1', N'MPS', N'Nghị Lực', N'Long An', '+33 8 61 52 51 ', 'Acker@example.com', 914)
INSERT dbo.DoanhNghiep(MaSoThue, LoaiHang, DiaChiKinhDoanh, QUAN, TenDoanhNghiep, NguoiDaiDien, ThanhPho, SoDT, Email, SLDonHang) VALUES (N'DN62', 'LH002', N'Cộng Hòa', N'Thanh Xuân', N'FedEx Freight', N'Ngọc Lý', N'Hồ Chí Minh', '+49 4043 163569', 'Asbury@example.com', 656)
INSERT dbo.DoanhNghiep(MaSoThue, LoaiHang, DiaChiKinhDoanh, QUAN, TenDoanhNghiep, NguoiDaiDien, ThanhPho, SoDT, Email, SLDonHang) VALUES (N'DN56', 'LH015', N'Hùng Vương', N'9', N'Boxberry Courier', N'Thắng Cảnh', N'Hồ Chí Minh', '+49-5717-273386', 'nlwccgg0@nowhere.com', 816)
INSERT dbo.DoanhNghiep(MaSoThue, LoaiHang, DiaChiKinhDoanh, QUAN, TenDoanhNghiep, NguoiDaiDien, ThanhPho, SoDT, Email, SLDonHang) VALUES (N'DN95', 'LH018', N'Trần Hưng Đạo', N'Phú Tài', N'TNT', N'Cẩm Nhung', N'Hồ Chí Minh', '+44 9639 145218', 'Chandler@example.com', 915)
INSERT dbo.DoanhNghiep(MaSoThue, LoaiHang, DiaChiKinhDoanh, QUAN, TenDoanhNghiep, NguoiDaiDien, ThanhPho, SoDT, Email, SLDonHang) VALUES (N'DN61', 'LH014', N'Cách Mạng Tháng 8', N'12', N'USPS First Class Mail', N'Thương Nga', N'Hồ Chí Minh', '+44 0396 303687', 'Bagwell@nowhere.com', 411)
INSERT dbo.DoanhNghiep(MaSoThue, LoaiHang, DiaChiKinhDoanh, QUAN, TenDoanhNghiep, NguoiDaiDien, ThanhPho, SoDT, Email, SLDonHang) VALUES (N'DN43', 'LH017', N'Nguyễn Thị Minh Khai', N'Phú Nhuận', N'USPS Express Mail', N'Gia Ðức', N'Hồ Chí Minh', '+44 6716 35 163', 'Quincy_Angel@example.com', 353)
INSERT dbo.DoanhNghiep(MaSoThue, LoaiHang, DiaChiKinhDoanh, QUAN, TenDoanhNghiep, NguoiDaiDien, ThanhPho, SoDT, Email, SLDonHang) VALUES (N'DN78', 'LH019', N'Âu Cơ', N'10', N'Boxberry Local Pickup', N'Nghị Quyền', N'Hồ Chí Minh', '+32 8 319 47 81', 'Abernathy797@example.com', 817)
INSERT dbo.DoanhNghiep(MaSoThue, LoaiHang, DiaChiKinhDoanh, QUAN, TenDoanhNghiep, NguoiDaiDien, ThanhPho, SoDT, Email, SLDonHang) VALUES (N'DN82', 'LH000', N'Lý Chính Thắng', N'Tân Phú', N'DHL', N'im Thư', N'Hồ Chí Minh', '+420 843 221 94', 'EltonStanton941@nowhere.com', 512)
INSERT dbo.DoanhNghiep(MaSoThue, LoaiHang, DiaChiKinhDoanh, QUAN, TenDoanhNghiep, NguoiDaiDien, ThanhPho, SoDT, Email, SLDonHang) VALUES (N'DN25', 'LH003', N'Trường Chinh', N'5', N'FedEx', N'Ngọc Lệ', N'Hồ Chí Minh', '+44 7019 56 450', 'EliasZPotts68@nowhere.com', 54)
INSERT dbo.DoanhNghiep(MaSoThue, LoaiHang, DiaChiKinhDoanh, QUAN, TenDoanhNghiep, NguoiDaiDien, ThanhPho, SoDT, Email, SLDonHang) VALUES (N'DN05', 'LH001', N'Lê Lai', N'11', N'Airmail Priority', N'Bảo An', N'Hồ Chí Minh', '+44 5620 21 610', 'Thornburg757@example.com', 916)
GO

--
-- Inserting data into table dbo.HopDong
--
INSERT dbo.HopDong(MaHD, NguoiDaiDien, SoChiNhanhDK, HieuLuc, PhanTramHH, NgayBatDau, MaDoanhNghiep, DangGiaHan) VALUES (N'HD000', N'Bạch Trà', 3, 1, 0.90555, '2021-04-02', 'DN56', 1)
INSERT dbo.HopDong(MaHD, NguoiDaiDien, SoChiNhanhDK, HieuLuc, PhanTramHH, NgayBatDau, MaDoanhNghiep, DangGiaHan) VALUES (N'HD001', N'Nhật Dũng', 8, 12, 0.10593, '2020-01-09', 'DN05', 0)
INSERT dbo.HopDong(MaHD, NguoiDaiDien, SoChiNhanhDK, HieuLuc, PhanTramHH, NgayBatDau, MaDoanhNghiep, DangGiaHan) VALUES (N'HD002', N'Nguyên Thảo', 0, 0, 0.49342, '2021-06-14', 'DN95', 1)
INSERT dbo.HopDong(MaHD, NguoiDaiDien, SoChiNhanhDK, HieuLuc, PhanTramHH, NgayBatDau, MaDoanhNghiep, DangGiaHan) VALUES (N'HD003', N'Thành Vinh', 10, 11, 0.07357, '2020-03-22', 'DN82', 1)
INSERT dbo.HopDong(MaHD, NguoiDaiDien, SoChiNhanhDK, HieuLuc, PhanTramHH, NgayBatDau, MaDoanhNghiep, DangGiaHan) VALUES (N'HD004', N'hánh My', 2, 10, 0.70843, '2021-09-05', 'DN37', 1)
INSERT dbo.HopDong(MaHD, NguoiDaiDien, SoChiNhanhDK, HieuLuc, PhanTramHH, NgayBatDau, MaDoanhNghiep, DangGiaHan) VALUES (N'HD005', N'Yến Phượng', 7, 8, 0.36872, '2020-06-18', 'DN95', 0)
INSERT dbo.HopDong(MaHD, NguoiDaiDien, SoChiNhanhDK, HieuLuc, PhanTramHH, NgayBatDau, MaDoanhNghiep, DangGiaHan) VALUES (N'HD006', N'�ức Khang', 9, 7, 0.58477, '2020-10-23', 'DN71', 1)
INSERT dbo.HopDong(MaHD, NguoiDaiDien, SoChiNhanhDK, HieuLuc, PhanTramHH, NgayBatDau, MaDoanhNghiep, DangGiaHan) VALUES (N'HD007', N'Thụy Long', 5, 6, 0.42997, '2020-01-10', 'DN78', 0)
INSERT dbo.HopDong(MaHD, NguoiDaiDien, SoChiNhanhDK, HieuLuc, PhanTramHH, NgayBatDau, MaDoanhNghiep, DangGiaHan) VALUES (N'HD008', N'Nguyết Ánh', 1, 9, 0.21333, '2020-08-30', 'DN95', 1)
INSERT dbo.HopDong(MaHD, NguoiDaiDien, SoChiNhanhDK, HieuLuc, PhanTramHH, NgayBatDau, MaDoanhNghiep, DangGiaHan) VALUES (N'HD009', N'Huy Thông', 4, 3, 0.84171, '2020-06-19', 'DN56', 1)
INSERT dbo.HopDong(MaHD, NguoiDaiDien, SoChiNhanhDK, HieuLuc, PhanTramHH, NgayBatDau, MaDoanhNghiep, DangGiaHan) VALUES (N'HD010', N'�ức Khiêm', 6, 2, 0.44835, '2020-08-31', 'DN25', 1)
GO

--
-- Inserting data into table dbo.ChiNhanh
--
INSERT dbo.ChiNhanh(MACHINHANH, MaDoanhNghiep, DiaChi, DoanhSoBan, MAHOPDONG) VALUES (N'CN639', N'DN25', N'Trường Chinh', 2026067, 'HD010')
INSERT dbo.ChiNhanh(MACHINHANH, MaDoanhNghiep, DiaChi, DoanhSoBan, MAHOPDONG) VALUES (N'CN830', N'DN78', N'Hùng Vương', 343, 'HD006')
INSERT dbo.ChiNhanh(MACHINHANH, MaDoanhNghiep, DiaChi, DoanhSoBan, MAHOPDONG) VALUES (N'CN357', N'DN95', N'Lê Lai', 36, 'HD009')
INSERT dbo.ChiNhanh(MACHINHANH, MaDoanhNghiep, DiaChi, DoanhSoBan, MAHOPDONG) VALUES (N'CN267', N'DN62', N'Lý Chính Thắng', 527, 'HD002')
INSERT dbo.ChiNhanh(MACHINHANH, MaDoanhNghiep, DiaChi, DoanhSoBan, MAHOPDONG) VALUES (N'CN867', N'DN62', N'Nguyễn Văn Cừ', 3, 'HD008')
INSERT dbo.ChiNhanh(MACHINHANH, MaDoanhNghiep, DiaChi, DoanhSoBan, MAHOPDONG) VALUES (N'CN867', N'DN03', N'Cộng Hòa', 4028316, 'HD007')
INSERT dbo.ChiNhanh(MACHINHANH, MaDoanhNghiep, DiaChi, DoanhSoBan, MAHOPDONG) VALUES (N'CN302', N'DN78', N'An Dương Vương', 7, 'HD001')
INSERT dbo.ChiNhanh(MACHINHANH, MaDoanhNghiep, DiaChi, DoanhSoBan, MAHOPDONG) VALUES (N'CN681', N'DN05', N'Lê Lợi', 1821603, 'HD000')
INSERT dbo.ChiNhanh(MACHINHANH, MaDoanhNghiep, DiaChi, DoanhSoBan, MAHOPDONG) VALUES (N'CN009', N'DN82', N'Trần Hưng Đạo', 7, 'HD003')
INSERT dbo.ChiNhanh(MACHINHANH, MaDoanhNghiep, DiaChi, DoanhSoBan, MAHOPDONG) VALUES (N'CN302', N'DN25', N'Nguyễn Thị Minh Khai', 698852, 'HD005')
INSERT dbo.ChiNhanh(MACHINHANH, MaDoanhNghiep, DiaChi, DoanhSoBan, MAHOPDONG) VALUES (N'CN613', N'DN37', N'Nguyễn Trãi', 1075797, 'HD004')
GO

--
-- Inserting data into table dbo.DonHang
--
INSERT dbo.DonHang(MaDH, PhiVanChuyen, TinhTrang, HinhThucThanhToan, PhiSanPham, NgayDat, DiaChiGiao, MACHINHANH, MaDoanhNghiep, MaKH, MaTX) VALUES (N'DH000', 31.8093, 0, 0, 54.7872, '2020-10-03 16:15:27.000', 'An Dương Vương', 'CN639', 'DN25', 'KH0036', 'TX015')
INSERT dbo.DonHang(MaDH, PhiVanChuyen, TinhTrang, HinhThucThanhToan, PhiSanPham, NgayDat, DiaChiGiao, MACHINHANH, MaDoanhNghiep, MaKH, MaTX) VALUES (N'DH001', 986.8485, 1, 1, 1905.6995, '2020-01-01 01:51:14.000', 'Cách Mạng Tháng 8', 'CN357', 'DN95', 'KH0031', 'TX013')
INSERT dbo.DonHang(MaDH, PhiVanChuyen, TinhTrang, HinhThucThanhToan, PhiSanPham, NgayDat, DiaChiGiao, MACHINHANH, MaDoanhNghiep, MaKH, MaTX) VALUES (N'DH002', 282.0009, 0, 1, 662.7319, '2020-07-23 09:03:27.000', 'Âu Cơ', 'CN613', 'DN37', 'KH0049', 'TX019')
INSERT dbo.DonHang(MaDH, PhiVanChuyen, TinhTrang, HinhThucThanhToan, PhiSanPham, NgayDat, DiaChiGiao, MACHINHANH, MaDoanhNghiep, MaKH, MaTX) VALUES (N'DH003', 382.001, 1, 0, 462.9004, '2020-03-13 09:03:15.000', 'Lê Lợi', 'CN681', 'DN05', 'KH0013', 'TX017')
INSERT dbo.DonHang(MaDH, PhiVanChuyen, TinhTrang, HinhThucThanhToan, PhiSanPham, NgayDat, DiaChiGiao, MACHINHANH, MaDoanhNghiep, MaKH, MaTX) VALUES (N'DH004', 131.8094, 2, 1, 241.8506, '2020-01-01 01:51:15.000', 'Lý Chính Thắng', 'CN830', 'DN78', 'KH0042', 'TX016')
INSERT dbo.DonHang(MaDH, PhiVanChuyen, TinhTrang, HinhThucThanhToan, PhiSanPham, NgayDat, DiaChiGiao, MACHINHANH, MaDoanhNghiep, MaKH, MaTX) VALUES (N'DH005', 31.8094, 2, 1, 159.9552, '2020-03-13 09:03:16.000', 'Trần Hưng Đạo', 'CN302', 'DN78', 'KH0004', 'TX011')
INSERT dbo.DonHang(MaDH, PhiVanChuyen, TinhTrang, HinhThucThanhToan, PhiSanPham, NgayDat, DiaChiGiao, MACHINHANH, MaDoanhNghiep, MaKH, MaTX) VALUES (N'DH006', 785.5396, 0, 0, 1890.5346, '2021-09-24 04:16:41.000', 'Nguyễn Văn Cừ', 'CN867', 'DN62', 'KH0037', 'TX004')
INSERT dbo.DonHang(MaDH, PhiVanChuyen, TinhTrang, HinhThucThanhToan, PhiSanPham, NgayDat, DiaChiGiao, MACHINHANH, MaDoanhNghiep, MaKH, MaTX) VALUES (N'DH007', 131.8095, 1, 1, 7.0535, '2020-11-14 06:10:31.000', 'Hùng Vương', 'CN267', 'DN62', 'KH0048', 'TX009')
INSERT dbo.DonHang(MaDH, PhiVanChuyen, TinhTrang, HinhThucThanhToan, PhiSanPham, NgayDat, DiaChiGiao, MACHINHANH, MaDoanhNghiep, MaKH, MaTX) VALUES (N'DH008', 886.8487, 1, 1, 516.7596, '2021-01-25 13:22:32.000', 'Nguyễn Trãi', 'CN867', 'DN03', 'KH0026', 'TX007')
INSERT dbo.DonHang(MaDH, PhiVanChuyen, TinhTrang, HinhThucThanhToan, PhiSanPham, NgayDat, DiaChiGiao, MACHINHANH, MaDoanhNghiep, MaKH, MaTX) VALUES (N'DH009', 31.8095, 1, 0, 1311.9465, '2020-01-01 01:51:16.000', 'Cộng Hòa', 'CN302', 'DN25', 'KH0019', 'TX005')
INSERT dbo.DonHang(MaDH, PhiVanChuyen, TinhTrang, HinhThucThanhToan, PhiSanPham, NgayDat, DiaChiGiao, MACHINHANH, MaDoanhNghiep, MaKH, MaTX) VALUES (N'DH010', 685.5396, 2, 1, 55.2468, '2020-03-13 09:03:17.000', 'Lê Lai', 'CN009', 'DN82', 'KH0014', 'TX008')
GO

--
-- Inserting data into table dbo.CHINHANH_SP
--
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP51811', N'CN357', N'DN95')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP32085', N'CN009', N'DN82')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP00526', N'CN302', N'DN78')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP89475', N'CN267', N'DN62')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP00526', N'CN867', N'DN03')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP02703', N'CN867', N'DN03')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP71060', N'CN639', N'DN25')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP00526', N'CN267', N'DN62')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP79902', N'CN830', N'DN78')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP95334', N'CN639', N'DN25')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP95334', N'CN830', N'DN78')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP32085', N'CN681', N'DN05')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP02876', N'CN009', N'DN82')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP89475', N'CN357', N'DN95')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP02703', N'CN009', N'DN82')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP32085', N'CN867', N'DN62')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP71060', N'CN267', N'DN62')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP51811', N'CN267', N'DN62')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP25169', N'CN302', N'DN25')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP24345', N'CN302', N'DN25')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP32085', N'CN302', N'DN78')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP00526', N'CN867', N'DN62')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP02703', N'CN302', N'DN25')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP79902', N'CN867', N'DN62')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP71060', N'CN867', N'DN62')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP24345', N'CN613', N'DN37')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP89475', N'CN830', N'DN78')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP02703', N'CN681', N'DN05')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP71060', N'CN357', N'DN95')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP02876', N'CN613', N'DN37')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP61357', N'CN613', N'DN37')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP79902', N'CN867', N'DN03')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP24345', N'CN009', N'DN82')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP32085', N'CN867', N'DN03')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP79902', N'CN267', N'DN62')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP02876', N'CN302', N'DN25')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP51811', N'CN867', N'DN03')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP76401', N'CN639', N'DN25')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP73373', N'CN639', N'DN25')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP89475', N'CN639', N'DN25')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP02703', N'CN302', N'DN78')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP51811', N'CN867', N'DN62')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP25169', N'CN613', N'DN37')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP51811', N'CN302', N'DN78')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP71060', N'CN830', N'DN78')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP24345', N'CN681', N'DN05')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP79902', N'CN357', N'DN95')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP76401', N'CN830', N'DN78')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP00526', N'CN681', N'DN05')
INSERT dbo.CHINHANH_SP(MASP, MACHINHANH, MADOANHNGHIEP) VALUES (N'SP95334', N'CN357', N'DN95')
GO

--
-- Inserting data into table dbo.DH_KH
--
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH002', N'KH0006')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH008', N'KH0008')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH006', N'KH0007')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH003', N'KH0003')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH005', N'KH0007')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH005', N'KH0009')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH000', N'KH0004')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH003', N'KH0007')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH001', N'KH0005')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH000', N'KH0002')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH001', N'KH0002')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH007', N'KH0008')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH008', N'KH0011')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH002', N'KH0003')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH008', N'KH0009')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH004', N'KH0008')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH003', N'KH0004')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH003', N'KH0006')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH009', N'KH0012')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH009', N'KH0010')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH006', N'KH0008')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH004', N'KH0007')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH009', N'KH0009')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH004', N'KH0005')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH004', N'KH0004')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH010', N'KH0010')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH001', N'KH0003')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH007', N'KH0009')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH002', N'KH0004')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH010', N'KH0011')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH010', N'KH0013')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH005', N'KH0005')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH008', N'KH0010')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH005', N'KH0008')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH003', N'KH0005')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH009', N'KH0011')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH005', N'KH0006')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH000', N'KH0001')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH000', N'KH0000')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH000', N'KH0003')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH006', N'KH0009')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH004', N'KH0006')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH010', N'KH0012')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH006', N'KH0006')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH001', N'KH0004')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH007', N'KH0010')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH002', N'KH0005')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH001', N'KH0001')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH007', N'KH0007')
INSERT dbo.DH_KH(MaDH, MaKH) VALUES (N'DH002', N'KH0002')
GO

--
-- Inserting data into table dbo.DONHANG_SP
--
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP51811', N'DH002', 853070285)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP32085', N'DH008', 1754966353)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP00526', N'DH006', 1230702594)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP89475', N'DH003', 638321920)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP00526', N'DH005', 853070286)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP02703', N'DH005', 366699348)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP71060', N'DH000', 1344494076)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP00526', N'DH003', 1015954229)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP79902', N'DH001', 638321921)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP95334', N'DH000', 1559242442)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP95334', N'DH001', 151950983)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP32085', N'DH007', 1344494077)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP02876', N'DH008', 366699349)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP89475', N'DH002', 1559242443)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP02703', N'DH008', 1230702595)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP32085', N'DH004', 151950984)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP71060', N'DH003', 853070287)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP51811', N'DH003', 1344494078)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP25169', N'DH009', 366699350)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP24345', N'DH009', 1559242444)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP32085', N'DH006', 638321922)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP00526', N'DH004', 1344494079)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP02703', N'DH009', 1015954230)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP79902', N'DH004', 1969714715)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP71060', N'DH004', 1230702596)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP24345', N'DH010', 1015954231)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP89475', N'DH001', 1754966354)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP02703', N'DH007', 853070288)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP71060', N'DH002', 1969714716)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP02876', N'DH010', 1230702597)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP61357', N'DH010', 1015954232)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP79902', N'DH005', 638321923)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP24345', N'DH008', 151950985)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP32085', N'DH005', 853070289)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP79902', N'DH003', 638321924)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP02876', N'DH009', 1230702598)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP51811', N'DH005', 1754966355)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP76401', N'DH000', 1559242445)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP73373', N'DH000', 853070290)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP89475', N'DH000', 366699351)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP02703', N'DH006', 638321925)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP51811', N'DH004', 1015954233)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP25169', N'DH010', 151950986)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP51811', N'DH006', 1969714717)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP71060', N'DH001', 1754966356)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP24345', N'DH007', 1969714718)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP79902', N'DH002', 366699352)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP76401', N'DH001', 853070291)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP00526', N'DH007', 638321926)
INSERT dbo.DONHANG_SP(MASP, MADH, SLSP) VALUES (N'SP95334', N'DH002', 1754966357)
GO

--
-- Inserting data into table dbo.TKDoanhNghiep
--
INSERT dbo.TKDoanhNghiep(ID, mk, trangthai, MADOANHNGHIEP) VALUES (N'DN79998', '48799', 0, 'DN56')
INSERT dbo.TKDoanhNghiep(ID, mk, trangthai, MADOANHNGHIEP) VALUES (N'DN36614', '34366', 0, 'DN03')
INSERT dbo.TKDoanhNghiep(ID, mk, trangthai, MADOANHNGHIEP) VALUES (N'DN79236', '14425', 1, 'DN62')
INSERT dbo.TKDoanhNghiep(ID, mk, trangthai, MADOANHNGHIEP) VALUES (N'DN62807', '22273', 1, 'DN78')
INSERT dbo.TKDoanhNghiep(ID, mk, trangthai, MADOANHNGHIEP) VALUES (N'DN11848', '90535', 1, 'DN95')
INSERT dbo.TKDoanhNghiep(ID, mk, trangthai, MADOANHNGHIEP) VALUES (N'DN33096', '59640', 1, 'DN37')
INSERT dbo.TKDoanhNghiep(ID, mk, trangthai, MADOANHNGHIEP) VALUES (N'DN74398', '58582', 0, 'DN71')
INSERT dbo.TKDoanhNghiep(ID, mk, trangthai, MADOANHNGHIEP) VALUES (N'DN21728', '83980', 1, 'DN43')
INSERT dbo.TKDoanhNghiep(ID, mk, trangthai, MADOANHNGHIEP) VALUES (N'DN02679', '63821', 0, 'DN25')
INSERT dbo.TKDoanhNghiep(ID, mk, trangthai, MADOANHNGHIEP) VALUES (N'DN68245', '89029', 0, 'DN61')
INSERT dbo.TKDoanhNghiep(ID, mk, trangthai, MADOANHNGHIEP) VALUES (N'DN76940', '08050', 1, 'DN82')
INSERT dbo.TKDoanhNghiep(ID, mk, trangthai, MADOANHNGHIEP) VALUES (N'DN88450', '92458', 0, 'DN05')
GO

--
-- Inserting data into table dbo.TKKhachHang
--
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH15997', '51388', 1, 'KH0047')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH81255', '06812', 1, 'KH0030')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH05951', '55984', 1, 'KH0025')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH47635', '84937', 0, 'KH0031')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH15244', '33450', 0, 'KH0004')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH89072', '98217', 0, 'KH0020')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH13649', '28314', 0, 'KH0049')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH76535', '81655', 0, 'KH0015')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH45026', '42407', 1, 'KH0035')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH10314', '38215', 0, 'KH0021')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH31792', '90110', 1, 'KH0045')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH40075', '31470', 1, 'KH0026')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH69891', '79271', 1, 'KH0010')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH40408', '50784', 0, 'KH0032')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH96157', '86263', 0, 'KH0041')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH72861', '14040', 0, 'KH0027')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH70693', '87472', 0, 'KH0048')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH82140', '35408', 1, 'KH0005')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH63514', '86185', 1, 'KH0046')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH83276', '69323', 1, 'KH0016')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH64509', '00797', 1, 'KH0011')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH74459', '63514', 1, 'KH0017')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH51502', '51459', 0, 'KH0022')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH73724', '12633', 1, 'KH0000')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH65554', '98826', 0, 'KH0036')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH29299', '17225', 1, 'KH0028')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH41840', '70528', 0, 'KH0006')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH54415', '87680', 0, 'KH0042')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH32522', '12988', 1, 'KH0023')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH32484', '86292', 1, 'KH0037')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH07033', '99900', 0, 'KH0029')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH66322', '06047', 0, 'KH0012')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH89384', '34156', 1, 'KH0044')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH11470', '22323', 1, 'KH0018')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH23702', '53248', 0, 'KH0024')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH35028', '47416', 0, 'KH0043')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH71096', '68309', 1, 'KH0013')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH04583', '04489', 0, 'KH0038')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH81573', '38493', 1, 'KH0001')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH41087', '28062', 1, 'KH0019')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH43961', '42182', 0, 'KH0033')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH02238', '51081', 0, 'KH0014')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH88216', '85992', 0, 'KH0039')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH84717', '65923', 0, 'KH0034')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH94798', '96067', 1, 'KH0040')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH35763', '49150', 1, 'KH0007')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH15966', '17967', 0, 'KH0002')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH65146', '43961', 0, 'KH0008')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH83193', '36533', 1, 'KH0003')
INSERT dbo.TKKhachHang(ID, MK, TrangThai, MaKH) VALUES (N'KH29094', '61882', 1, 'KH0009')
GO

--
-- Inserting data into table dbo.TKNHANVIEN
--
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV64666', '90860', 1, 'NV012')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV38809', '56367', 0, 'NV009')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV18592', '18808', 0, 'NV005')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV91003', '01588', 0, 'NV028')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV98003', '52370', 0, 'NV029')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV53088', '93024', 1, 'NV019')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV08621', '91252', 0, 'NV016')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV08582', '13745', 1, 'NV024')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV55933', '70858', 0, 'NV021')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV61387', '28277', 1, 'NV002')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV19735', '39331', 1, 'NV020')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV68412', '38794', 0, 'NV025')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV04893', '94897', 0, 'NV006')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV45329', '65272', 0, 'NV013')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV02786', '35821', 0, 'NV003')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV46347', '63329', 0, 'NV022')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV23970', '36299', 1, 'NV017')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV30254', '86934', 1, 'NV026')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV88434', '32239', 0, 'NV023')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV91630', '70586', 0, 'NV000')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV47384', '84218', 1, 'NV014')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV48941', '84340', 0, 'NV027')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV08189', '05524', 1, 'NV018')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV02512', '24738', 1, 'NV004')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV59437', '49135', 1, 'NV010')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV20748', '51008', 0, 'NV015')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV00345', '18917', 1, 'NV007')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV25287', '36941', 1, 'NV001')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV45439', '59437', 1, 'NV011')
INSERT dbo.TKNHANVIEN(ID, MK, TRANGTHAI, MANV) VALUES (N'NV09071', '92455', 1, 'NV008')
GO

--
-- Inserting data into table dbo.TKTAIXE
--
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX08455', '44886', 1, 0, 'TX015')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX72468', '77994', 1, 1, 'TX007')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX52189', '78144', 0, 0, 'TX012')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX23536', '10411', 1, 1, 'TX019')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX72877', '22765', 0, 0, 'TX018')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX10992', '26717', 0, 1, 'TX003')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX83292', '97921', 0, 1, 'TX017')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX42805', '83292', 1, 0, 'TX005')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX87746', '42308', 0, 1, 'TX010')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX24267', '38774', 0, 0, 'TX001')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX57217', '60975', 0, 1, 'TX016')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX81666', '86357', 1, 0, 'TX008')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX58527', '21704', 1, 1, 'TX004')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX70233', '96576', 0, 1, 'TX002')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX51950', '95705', 1, 0, 'TX006')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX16571', '63318', 0, 1, 'TX013')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX97611', '36519', 1, 0, 'TX009')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX15552', '50699', 1, 0, 'TX000')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX43197', '73181', 0, 1, 'TX011')
INSERT dbo.TKTAIXE(ID, MK, TRANGTHAI, THIENTHECHAN, MATX) VALUES (N'TX04165', '83086', 0, 0, 'TX014')
GO

--
-- Inserting data into table dbo.TX_DH
--
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH002', N'TX006')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH008', N'TX008')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH006', N'TX007')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH003', N'TX003')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH005', N'TX007')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH005', N'TX009')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH000', N'TX004')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH003', N'TX007')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH001', N'TX005')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH000', N'TX002')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH001', N'TX002')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH007', N'TX008')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH008', N'TX011')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH002', N'TX003')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH008', N'TX009')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH004', N'TX008')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH003', N'TX004')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH003', N'TX006')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH009', N'TX012')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH009', N'TX010')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH006', N'TX008')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH004', N'TX007')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH009', N'TX009')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH004', N'TX005')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH004', N'TX004')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH010', N'TX010')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH001', N'TX003')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH007', N'TX009')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH002', N'TX004')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH010', N'TX011')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH010', N'TX013')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH005', N'TX005')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH008', N'TX010')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH005', N'TX008')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH003', N'TX005')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH009', N'TX011')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH005', N'TX006')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH000', N'TX001')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH000', N'TX000')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH000', N'TX003')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH006', N'TX009')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH004', N'TX006')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH010', N'TX012')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH006', N'TX006')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH001', N'TX004')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH007', N'TX010')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH002', N'TX005')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH001', N'TX001')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH007', N'TX007')
INSERT dbo.TX_DH(MaDH, MaTX) VALUES (N'DH002', N'TX002')
GO

--
-- Set NOEXEC to off
--

SET NOEXEC OFF
GO