USE MASTER
GO

CREATE DATABASE Nhom18_DoAnThucHanh_19HTT2
GO

Use Nhom18_DoAnThucHanh_19HTT2
go

CREATE TABLE SANPHAM(
	MASP VARCHAR(50) NOT NULL,
	TENSP NVARCHAR(100) NOT NULL,
	GIA SMALLMONEY NOT NULL,
	CONSTRAINT PK_SANPHAM PRIMARY KEY(MASP)
);
GO

CREATE TABLE CHINHANH_SP(
	MASP VARCHAR(50) NOT NULL,
	MACHINHANH VARCHAR(5) NOT NULL,
	MADOANHNGHIEP VARCHAR(50) NOT NULL,
	CONSTRAINT PK_CHINHANH_SP PRIMARY KEY(MASP, MACHINHANH, MADOANHNGHIEP)
);
GO					

CREATE TABLE DONHANG_SP(
	MASP VARCHAR(50) NOT NULL,
	MADH VARCHAR(50) NOT NULL,
	SLSP INT CHECK(SLSP > 0) NOT NULL,
	CONSTRAINT PK_DONHANG_SP PRIMARY KEY(MASP, MADH)
);
GO


CREATE TABLE TKTAIXE(
	ID VARCHAR(50) NOT NULL,
	MK VARCHAR(50) NOT NULL,
	TRANGTHAI INT CHECK (TRANGTHAI IN (0, 1)),
	THIENTHECHAN BIT,
	MATX VARCHAR(50) NOT NULL
	CONSTRAINT PK_TKTAIXE PRIMARY KEY(ID)
);
GO

CREATE TABLE TAIXE(
	MATX VARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(50)NOT NULL,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	BIENSOXE VARCHAR(50) NOT NULL UNIQUE,
	TKNH VARCHAR(50) NOT NULL,
	KHUVUCHD NVARCHAR(50) NOT NULL,
	SDT VARCHAR(15) NOT NULL UNIQUE,
	CONSTRAINT PK_TAIXE PRIMARY KEY(MATX)
);
GO

CREATE TABLE DoanhNghiep(
  MaSoThue VARCHAR(50) NOT NULL,
  LoaiHang NVARCHAR(100) NOT NULL,
  DiaChiKinhDoanh NVARCHAR(500) NOT NULL,
  QUAN NVARCHAR(50) NOT NULL,
  TenDoanhNghiep NVARCHAR(100) NOT NULL,
  NguoiDaiDien NVARCHAR(50) NOT NULL,
  ThanhPho NVARCHAR(50) NOT NULL,
  SoDT VARCHAR(15) NOT NULL UNIQUE,
  Email VARCHAR(50) NOT NULL UNIQUE,
  SLDonHang INT CHECK(SLDonHang >=0)
  PRIMARY KEY (MaSoThue)
);
GO

CREATE TABLE HopDong(
  MaHD VARCHAR(50) NOT NULL,
  NguoiDaiDien NVARCHAR(50) NOT NULL,
  SoChiNhanhDK INT CHECK (SoChiNhanhDK >=0) NOT NULL,
  HieuLuc INT CHECK(HieuLuc >=0) NOT NULL,
  PhanTramHH FLOAT CHECK (0 < PhanTramHH and PhanTramHH <= 1 ) NOT NULL,
  NgayBatDau DATE NOT NULL,
  MaDoanhNghiep VARCHAR(50) NOT NULL
  PRIMARY KEY(MaHD)
);
GO

CREATE TABLE TKDoanhNghiep(
  ID VARCHAR(50) NOT NULL,
  mk VARCHAR(50) NOT NULL,
  trangthai INT CHECK(0 <= trangthai and trangthai <= 1) NOT NULL,
  MADOANHNGHIEP VARCHAR(50),
  PRIMARY KEY(ID)
)
GO

CREATE TABLE ChiNhanh(
  MaChiNhanh VARCHAR(5) NOT NULL,
  MaDoanhNghiep VARCHAR(50) NOT NULL,
  DiaChi NVARCHAR(200) NOT NULL,
  DoanhSoBan MONEY,
  MAHOPDONG VARCHAR(50),
  PRIMARY KEY(MaChiNhanh, MaDoanhNghiep)
)
GO		


create table KhachHang (
	MaKH 	varchar(50) not null,
	HoTen 	nvarchar(100),
	SDT 	varchar(10) UNIQUE,
	DiaChi 	varchar(50),
	Email 	VARCHAR(50) UNIQUE,
	primary key (MaKH)	
)
GO	

create table TKKhachHang
(
	ID 	varchar(50) NOT NULL,
	MK varchar(50) NOT NULL,
	TrangThai int CHECK (0 <= TRANGTHAI AND TRANGTHAI <= 1),
	MaKH varchar(50),
	primary key (ID)
)
GO		

create table DH_KH
(
	MaDH varchar(50) not null,
	MaKH varchar(50) not null,
	primary key (MaDH, MaKH)
)
GO

create table TX_DH
(
	MaTX varchar(50) not null,
	MaDH varchar(50) not null,
	primary key (MaDH, MaTX)
)
GO

create table DonHang
(
	MaDH varchar(50) not null,
	PhiVanChuyen  smallmoney,
	TinhTrang  int CHECK (0 <= TINHTRANG AND TINHTRANG <= 2),
	HinhThucThanhToan  int CHECK (0 <= HINHTHUCTHANHTOAN AND HINHTHUCTHANHTOAN <= 1),
	PhiSanPham  smallmoney,
	NgayDat Datetime,
	DiaChiGiao varchar(50) not NULL,
	MaChiNhanh varchar(5) not NULL,
	MaDoanhNghiep varchar(50) not NULL,
	MaKH varchar(50) not NULL,
	MaTX varchar(50) not NULL,
	primary key(MaDH)
)
GO


CREATE TABLE NHANVIEN(
	MANV VARCHAR(10) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	DIACHI VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	SDT VARCHAR(15) NOT NULL UNIQUE,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
);
GO

CREATE TABLE TKNHANVIEN(
	ID VARCHAR(50) NOT NULL,
	MK VARCHAR(50) NOT NULL,
	TRANGTHAI INT CHECK(0 <= TRANGTHAI AND TRANGTHAI <= 1),
	MANV VARCHAR(10) NOT NULL,
	CONSTRAINT PK_TKNHANVIEN PRIMARY KEY(ID)
);
GO				


--Create foreign key

--Foreign key of TKNHANVIEN
ALTER TABLE TKNHANVIEN	
ADD CONSTRAINT FK_TKNHANVIEN
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
GO

--Foreign key of TKDoanhNghiep
ALTER TABLE TKDOANHNGHIEP	
ADD CONSTRAINT FK_TKDOANHNGHIEP
FOREIGN KEY (MADOANHNGHIEP) REFERENCES DOANHNGHIEP(MASOTHUE);
GO

--FOREIGN KEY OF CHINHANH
ALTER TABLE CHINHANH			
ADD CONSTRAINT FK_CHINHANH
FOREIGN KEY (MADOANHNGHIEP) REFERENCES DOANHNGHIEP(MASOTHUE);
GO

ALTER TABLE CHINHANH			
ADD CONSTRAINT FK_CHINHANH_MAHOPDONG
FOREIGN KEY (MAHOPDONG) REFERENCES HOPDONG(MAHD);
GO

--FOREIGN KEY OF HOPDONG
ALTER TABLE HOPDONG
ADD CONSTRAINT FK_HOPDONG
FOREIGN KEY(MADOANHNGHIEP) REFERENCES DOANHNGHIEP(MASOTHUE)
GO

--FOREIGN KEY OF CHINHANH_SP
ALTER TABLE CHINHANH_SP
ADD CONSTRAINT FK_CHINHANH_SP_MACHINHANH_MADOANHNGHIEP
FOREIGN KEY(MACHINHANH, MADOANHNGHIEP) REFERENCES CHINHANH(MACHINHANH, MADOANHNGHIEP)
GO

ALTER TABLE CHINHANH_SP
ADD CONSTRAINT FK_CHINHANH_SP_MASP	
FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)
GO

--FOREIGN KEY OF DONHANG_SP
ALTER TABLE DONHANG_SP	
ADD CONSTRAINT FK_DONHANG_SP_masp				
FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)
GO

ALTER TABLE DONHANG_SP	
ADD CONSTRAINT FK_DONHANG_SP_MADH
FOREIGN KEY(MADH) REFERENCES DONHANG(MADH)
GO
--FOREIGN KEY OF TKTAIXE
ALTER TABLE TKTAIXE			
ADD CONSTRAINT FK_TKTAIXE_TAIXE
FOREIGN KEY(MATX) REFERENCES TAIXE(MATX)
GO

--FOREIGN KEY OF TX_DH
ALTER TABLE TX_DH			
ADD CONSTRAINT FK_TXDH_TAIXE1
FOREIGN KEY(MADH) REFERENCES DONHANG(MADH)
GO														


ALTER TABLE TX_DH			
ADD CONSTRAINT FK_TXDH_TAIXE2
FOREIGN KEY(MATX) REFERENCES TAIXE(MATX)
GO

--FOREIGN KEY OF DH_KH
ALTER TABLE DH_KH
ADD CONSTRAINT FK_DHKH_DONHANG
FOREIGN KEY(MADH) REFERENCES DONHANG(MADH)
GO

ALTER TABLE DH_KH							
ADD CONSTRAINT FK_DHKH_KHACHHANG
FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
GO

--FOREIGN KEY OF TKKHACHHANG
ALTER TABLE TKKHACHHANG						
ADD CONSTRAINT FK_TKkhachHang_KhachHang
FOREIGN KEY(MAKH) REFERENCES KhachHang(MaKH)
GO

--FOREIGN KEY OF DONHANG
ALTER TABLE DONHANG											
ADD CONSTRAINT FK_DONHANG_CHINHANH
FOREIGN KEY(MACHINHANH, MADOANHNGHIEP) REFERENCES CHINHANH(MACHINHANH, MADOANHNGHIEP)
GO

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_KHACHHANG
FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
GO

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_TAIXE
FOREIGN KEY(MATX) REFERENCES TAIXE(MATX)
GO








